### ISSUE TITLE
参考文献字体

### ISSUE THREAD

**Issue by UAMYEVTHING** [BlueFisher/shuthesis#10]
能不能把参考文献四个字的字体修改为和前面章节不同的，即 第一章用宋体，参考文献用黑体，定位到shuthesis.dtx里面强制修改，出现报错

**Comment by BlueFisher** [comment]
`\shu@chapter*{\heiti\bibname}%` 应该就行吧

**Comment by UAMYEVTHING** [comment]
确实可以，谢谢。如果想同时改变这里的字号的话有没有什么方法呢，直接\shu@chapter*{\heiti\sanhao\bibname}%的话字号可以改，可目录中这几个字也会跟着变，和别的不一致
