### ISSUE TITLE
图片引用

### ISSUE THREAD

**Issue by joyh9** [BlueFisher/shuthesis#11]
在插入第一个图片的时候，编号为1.1  第二个图片的时候编号为1.2  但是在交叉引用图片二的时候，为啥显示的还是1.1

**Comment by BlueFisher** [comment]
可以贴一下具体的`/label`和`/ref`的代码，我目前没有遇到过这个问题

**Comment by joyh9** [comment]
是我搞错了 `\label`的位置放错了（笑哭）。不过还有一个问题 就是好像在段中的时候，如果第二排是接的上一排的字母单词的话，会相比上一排突出一个字母的身位 无法对齐，这是什么原因呢

**Comment by joyh9** [comment]
是我搞错了 `\label`的位置放错了（笑哭）。不过还有一个问题 就是好像在段中的时候，如果第二排是接的上一排的字母单词的话，会相比上一排突出一个字母的身位 无法对齐，这是什么原因呢

**Comment by BlueFisher** [comment]
不清楚你指的问题是什么，可否贴一张图片

**Comment by joyh9** [comment]
抱歉！我不知道啥原因，现在又好像没有问题了。耽误学长时间了（笑哭）
