### ISSUE TITLE
使用vs code运行后报错

### ISSUE THREAD

**Issue by makeyourhandsdirty** [BlueFisher/shuthesis#12]
显示 option clash for package natbib。感觉是和gbt7714那个包冲突了，但是不知道怎么解决。麻烦博主解答一下。

**Comment by BlueFisher** [comment]
这个跟vscode没有关系，大概率是texlive的包没有更新的问题，因为natbib这个包有一次大更新，之前的不兼容。建议你打开texlive升级更新下

**Comment by makeyourhandsdirty** [comment]
嗯 确实解决了 还有一个问题 运行完模版这边 显示 citation '文章名' 未定义 这个问题怎么解决

**Comment by makeyourhandsdirty** [comment]
成功解决 感谢解答！
