### ISSUE TITLE
如何修改参考文献的格式

### ISSUE THREAD

**Issue by LoieSun** [BlueFisher/shuthesis#15]
你好，
我想请教下如何修改参考文献的格式，默认方法生成的参考文献：
GHOSE S, PREVOST J J. Autofoley: Artificial synthesis of synchronized sound tracks for silent videos with deep learning[J]. IEEE Transactions on Multimedia, 2020, 23: 1895-1907

我期望的格式：
Ghose S, Prevost J J. Autofoley: Artificial synthesis of synchronized sound tracks for silent videos with deep learning[J]. IEEE Transactions on Multimedia, 2020, 23: 1895-1907.
 
感谢！

**Comment by BlueFisher** [comment]
你可以查看 https://github.com/BlueFisher/shuthesis/commit/d35ae3fa77e7aaf6c8b9f33599e03fc1be0ab188 这个commit之前的版本，参考文献格式中的作者名称是小写的。

但之前的参考文献格式不符合 GB/T 7714-2015 的规范，所以之后改了。

**Comment by LoieSun** [comment]
收到！非常感谢！
