### ISSUE TITLE
生僻字问题

### ISSUE THREAD

**Issue by LoieSun** [BlueFisher/shuthesis#16]
hi，

由于我的名字中有不常用汉字，祎，所以无法正常显示
尝试过几个方法以后并不能完全解决，比如换字体包，生僻字可以显示但比普通汉字高一些

感谢您的帮助，期待您的回复！

**Comment by BlueFisher** [comment]
你好，祎 这个字目前测试下来没有发现问题
![image](https://github.com/BlueFisher/shuthesis/assets/6104460/c6628e4f-7841-4894-acda-cfad9878c289)
![image](https://github.com/BlueFisher/shuthesis/assets/6104460/79ff8305-94f5-4ef9-ab75-36646aa0d126)

**Comment by LoieSun** [comment]
谢谢您的回复，我这边显示如图：
<img width="73" alt="image" src="https://github.com/BlueFisher/shuthesis/assets/40746799/e06445a1-8d3a-4d2f-a1cd-3fc8eda2cc10">

**Comment by BlueFisher** [comment]
可能你的系统的楷书字体不包含`祎`这个字，windows系统中的楷书有这个字。
`ctex`宏包会根据系统自动寻找默认的楷书字体，所以你需要重新设置默认的楷书字体。
建议你下载windows默认的楷书字体，比如 `simkai.ttf` 放到文章根目录下，并在 `main.tex` 的 `\usepackage{shuthesis}` 下添加
```
\setCJKfamilyfont {kaishu} {simkai.ttf}
\renewcommand{\kaishu}{\CJKfamily{kaishu}}
```
这样就能覆盖 `\kaishu`字体

**Comment by LoieSun** [comment]
非常感谢您的帮助！我按照您说的方法尝试了，可以正常显示了
另外在远程性声明的上面和学术成果里面，需要的是宋体，还是不可以正常显示
<img width="30" alt="image" src="https://github.com/BlueFisher/shuthesis/assets/40746799/f8e279aa-837d-44b9-83a2-aaa41146ba5b">
想问下，这里我该如何修改呢

麻烦啦！

**Comment by BlueFisher** [comment]
与楷书的问题相同，需要将宋体放到根目录下，比如 `simsun.ttc`
因为宋体是全文的默认字体，所以需要设置
```
\setCJKmainfont{simsun.ttc}
```

**Comment by LoieSun** [comment]
全部解决了，非常感谢您的耐心帮助！
