### ISSUE TITLE
Cover:  new cover of professional master 

### ISSUE THREAD

**Issue by CaiCandong** [BlueFisher/shuthesis#17]
Description:
In the current code it only distinguishes between Masters/PhDs. Perhaps a cover should be added for Professional Masters?

> https://gs.shu.edu.cn/pygl.htm

![image](https://github.com/BlueFisher/shuthesis/assets/50507092/4c12489d-68c2-48bd-941c-9c339a56a07b)

**Comment by BlueFisher** [comment]
https://github.com/BlueFisher/shuthesis/commit/75b1999e3738116b60c0d095a44530bac19ce94c
`\documentclass[type=profmaster,openany,pifootnote]{shuthesis}`

**Comment by CaiCandong** [comment]
Thank you very much for your quick response!
