### ISSUE TITLE
博士论文封面字体错误

### ISSUE THREAD

**Issue by flowingrain** [BlueFisher/shuthesis#18]
研究生院官网word版本中，作者、学科专业、导师、完成日期等信息中文为黑体二号，英文与数字为Times New Roman二号。第二页上海大学为黑体二号。第三页“上海大学学位论文原创性声明”及“上海大学学位论文使用授权说明”为黑体三号。学位论文作者签名与日期上下分布，授权说明中作者签名与导师签名日期互相独立。

**Comment by BlueFisher** [comment]
粗略的先更新封面：https://github.com/BlueFisher/shuthesis/commit/fb1f0c7f27a25710998187647aeba546ce600586
