### ISSUE TITLE
图片和表格题目问题

### ISSUE THREAD

**Issue by Keelyn-Themis** [BlueFisher/shuthesis#20]
您好，在新版的毕业论文模板中，

1. 要求图片和表格都同时含有中文和英文形式的表题；
2. 需要续表的情况，模板中是再次重复了表题等部分，并且表序不变；
3. 论文封面的“题目”两字和正式题目是同样的字体；
![7c2fd0c1b1beda2dd111802abc03c17](https://github.com/BlueFisher/shuthesis/assets/93172501/01b33be2-bc30-49db-9d53-5b23641a8ca7)

![ebcda163068231b156109e1c42ecc44](https://github.com/BlueFisher/shuthesis/assets/93172501/e7c9d066-e1dd-435b-8f55-dcc436611430)

如图所示，不知道这个些应该怎么修改呢？请求您的帮助，谢谢！

**Comment by BlueFisher** [comment]
中英文caption已在 https://github.com/BlueFisher/shuthesis/commit/984813d961df219baeda3b1e426eb5c565e44d72 中新增该功能，原来的 `\caption{xxx}` 变为 `\bicaption{中文xxx}{英文xxx}`即可

续表的话建议自行使用额外的宏包，比如 longtable 来解决

`题目` 可以暂时性的将 [这一行](https://github.com/BlueFisher/shuthesis/blob/4c0783c2fe2279250f4fbf4f2fcde8088987e9d2/shuthesis.cls#L473C49-L473C49) 替换为
```
\zihao{-2}\ifxetex\LanTingHei\else\bfseries\heiti\fi\makecell{题\\ 目}
```

**Comment by Keelyn-Themis** [comment]
已解决，非常感谢！
