### ISSUE TITLE
pdf标题问题

### ISSUE THREAD

**Issue by karsalee** [BlueFisher/shuthesis#21]
在生成pdf后查看pdf，在标题栏怎么有两个中文摘要和两个英文ABSTRACT呀？这个问题能看看吗？
![image](https://github.com/BlueFisher/shuthesis/assets/49475192/c82c018a-4fab-4b67-9467-9a755c25ac54)

**Comment by BlueFisher** [comment]
已修复 https://github.com/BlueFisher/shuthesis/commit/c9e42476f9254706c194651acbfb9f0a5050946b

**Comment by karsalee** [comment]
感谢
