### ISSUE TITLE
多子图如何分别给予各自独立的label？

### ISSUE THREAD

**Issue by haikunzhang95** [BlueFisher/shuthesis#22]
您好：
多子图使用\captionbox命令时候如何给予两个子图独立的label？我看模板里面没有说明，自己试了在不同位置给\label，但是正文引用不正确，都是问号。
比如下面的代码：
\begin{figure}[!htbp]
	\centering
	\captionbox{图1}{
		\includegraphics[scale=0.35]{ch4/fig4-3.pdf}
	}
	\captionbox{图2}{
		\includegraphics[scale=0.3]{ch4/fig4-4.pdf}
	}
\end{figure}
怎么给予两个图的label呢？
谢谢！

**Comment by BlueFisher** [comment]
```
\begin{figure}[!htbp]
\centering
\captionbox{图1 \label{fig:aaa}}{
\includegraphics[scale=0.35]{ch4/fig4-3.pdf}
}
\captionbox{图2 \label{fig:bbb}}{
\includegraphics[scale=0.3]{ch4/fig4-4.pdf}
}
\end{figure}
```

**Comment by haikunzhang95** [comment]
> ```
> \begin{figure}[!htbp]
> \centering
> \captionbox{图1 \label{fig:aaa}}{
> \includegraphics[scale=0.35]{ch4/fig4-3.pdf}
> }
> \captionbox{图2 \label{fig:bbb}}{
> \includegraphics[scale=0.3]{ch4/fig4-4.pdf}
> }
> \end{figure}
> 
THank U
