### ISSUE TITLE
”证明“的格式有问题怎么解决？

### ISSUE THREAD

**Issue by guangjinpan** [BlueFisher/shuthesis#23]
如图，证明的格式，在最后一行的最后面，会多一个正方形□。这种该怎么解决？
![image](https://github.com/BlueFisher/shuthesis/assets/35365588/8c47f310-4df0-494c-8bbd-0b79c109888a)

**Comment by BlueFisher** [comment]
这是正常现象，表示证明完毕的符号

**Comment by guangjinpan** [comment]
理解，感谢！
