### ISSUE TITLE
关于对算法进行编号的问题

### ISSUE THREAD

**Issue by guangjinpan** [BlueFisher/shuthesis#24]
发现算法编号不会按照章节重置。以下给出了一种可能的解决方案：
在shuthesis.cfg 48行
\renewcommand{\algorithmcfname}{算法}
后面添加如下：

\makeatletter
\@addtoreset{algocf}{chapter}
\makeatother
\renewcommand{\thealgocf}{\thechapter.\arabic{algocf}}

可以修改成功

**Comment by guangjinpan** [comment]
最新测试，这样直接引入可能会导致第一页报错。有其他解决办法可以互相讨论

**Comment by BlueFisher** [comment]
https://github.com/BlueFisher/shuthesis/commit/ac6745773c5e54a9b1ab578676ff912a2d3242a9
