### ISSUE TITLE
bicaption 行距不一致

### ISSUE THREAD

**Issue by yzx9** [BlueFisher/shuthesis#25]
由于模版设置了 bicaption 的 skip 大小

```latex
\DeclareBiCaptionSeparator{skip}{\vspace{-5bp}}
```

会导致多行的 caption 时，行距不一致：

<img width="460" alt="image" src="https://github.com/BlueFisher/shuthesis/assets/41458459/3fc68c3f-738e-4d57-81e9-b70bb1ab9bec">

## Possiable Solution

1. 删除间距

```latex
\DeclareBiCaptionSeparator{skip}{\vspace{-5bp}}
```

2. 缩小行距

```latex
\captionsetup[figure]{font={stretch=.7826}} % (23 - 5) / 23
```

**Comment by BlueFisher** [comment]
已删除 `BiCaptionSeparator` https://github.com/BlueFisher/shuthesis/commit/8b3e10d669959aa74de321c5bf07d8aa8d9f87dc

**Comment by BlueFisher** [comment]
如果对行距不满意，可以在 `bicaption` 中添加 `vspace{xx}` 手动控制间距
