### ISSUE TITLE
有关目录格式问题

### ISSUE THREAD

**Issue by Au21ke** [BlueFisher/shuthesis#26]
该模板最新版本的latex目录好像都是加粗黑体，但是要求好像并不是都加粗，请问一下怎么修改呀，谢谢啦
<img width="379" alt="fe24579f7a32ac07f89a7c001aebe8a" src="https://github.com/BlueFisher/shuthesis/assets/122142557/46c6156b-3dab-4e42-ae63-f8441b27a341">

**Comment by BlueFisher** [comment]
在[略微缩小行距，微调目录字体](https://github.com/BlueFisher/shuthesis/commit/7127318d454fcdf0b729dfde33c79db6f78816f5)这个commit后，都是黑体+宋体的组合，与word版确实有所不同。

如有需要可以手动调整 `shuthesis.cls` 中的
```
\patchcmd{\@dottedtocline}{#4}{\csname shu@toc@font\endcsname #4}{}{}
```

但从实际效果看，现在版本的目录更美观，且全文并没有黑体加粗这种特殊选项。
学校的word模板也不是一定要全部完全一样。比如现在word中有`摘要`，`ABSTRACT`两项，但在预答辩时，校外专家却建议去掉这两个，说是不符合论文规范。
