### ISSUE TITLE
为什么专硕模板中答辩委员会签名会分成两页显示

### ISSUE THREAD

**Issue by cocohao715** [BlueFisher/shuthesis#28]
![image](https://github.com/BlueFisher/shuthesis/assets/32030622/9606e7d8-037d-4631-a354-76253b6c3044)
为什么专硕的答辩委员会签名会分成两页显示

**Comment by BlueFisher** [comment]
因为`专业硕士`是四个字，导致`本论文经答辩...`这一段超了一行😅。已记录问题

**Comment by cocohao715** [comment]
嗯嗯，我已经修改了。把委员和导师之间的\vskip5cm改成了\vskip4cm
