### ISSUE TITLE
封面的英文最新模板给的是DOCTORAL

### ISSUE THREAD

**Issue by Resurgence3** [BlueFisher/shuthesis#29]
名字信息之类的现在是靠左对齐了

**Comment by BlueFisher** [comment]
已记录问题，可以临时在`shuthesis.cls`中的 `459-465` 修改

**Comment by Resurgence3** [comment]
谢谢呀，还有一个问题是英文那部份“A Dissertation Submitted to Shanghai University for the Degree of Doctor in Science”，我看现在改成了“A Dissertation Submitted to Shanghai University for the Degree of Doctor **of Philosophy** in Science”，多加了两个单词
