### ISSUE TITLE
参考文献title大小写会被改成以首字母大写，其它都变成小写

### ISSUE THREAD

**Issue by cocohao715** [BlueFisher/shuthesis#30]
参考文献title大小写会被改成以首字母大写，其它都变成小写
![image](https://github.com/BlueFisher/shuthesis/assets/32030622/2cb03740-5bc3-49d9-adc0-f63c9f882b64)
![image](https://github.com/BlueFisher/shuthesis/assets/32030622/685ce002-b193-4336-acb4-25e2b4d98074)

**Comment by BlueFisher** [comment]
这是GB/T 7714—2015的格式要求，如果一定要大写，可以在title里将大写字母用花括号，比如
```
title={Multiple {V}iew {G}exxx}
```

**Comment by cocohao715** [comment]
嗯嗯，问了已送审的同学，确实没问题
