### ISSUE TITLE
请问如何将第二个封面的标题在中间地方回车

### ISSUE THREAD

**Issue by cocohao715** [BlueFisher/shuthesis#31]
![image](https://github.com/BlueFisher/shuthesis/assets/32030622/a053a4c9-70d1-41e9-997d-ae5a58f0267a)

**Comment by BlueFisher** [comment]
一种方法是在 `\shusteup` 的 `ctitle` 加 `\\` 强制换行
如果想要封面和第二封面的换行位置不一样的话，目前只能强制修改 `shuthesis.cls` 中的
```
\begin{center}\yihao[1.5]{\bfseries{\shu@ctitle}}\end{center}
```
把 `\shu@ctitle` 替换为你的论文题目，并在适当的地方用 `\\` 换行

**Comment by cocohao715** [comment]
好的，谢谢大佬
