### ISSUE TITLE
关于参考文献显示问题

### ISSUE THREAD

**Issue by cocohao715** [BlueFisher/shuthesis#32]
![image](https://github.com/BlueFisher/shuthesis/assets/32030622/e6c05713-d5be-421e-bc0a-3340d7a9df5d)
![image](https://github.com/BlueFisher/shuthesis/assets/32030622/61e9d367-575d-4a27-afb5-d1afec52c339)
![image](https://github.com/BlueFisher/shuthesis/assets/32030622/79f98497-eed2-45ed-9b79-ea1f7863ee94)
参考文献跟google学术里得引用显示不一样

**Comment by BlueFisher** [comment]
建议参考 **《GB T 7714-2015 信息与文献—参考文献著录规则》**
