### ISSUE TITLE
latex生成得论文图和表是被加粗的，而模板中的图和表是没有加粗的

### ISSUE THREAD

**Issue by cocohao715** [BlueFisher/shuthesis#33]
![image](https://github.com/BlueFisher/shuthesis/assets/32030622/630a6fee-675f-455d-868b-97e7c06c0b34)
latex生成得论文图和表是被加粗的，而模板中的图和表是没有加粗的

**Comment by BlueFisher** [comment]
```
\DeclareCaptionLabelFormat{shu}{{\dawu[1.5]\heiti #1~\rmfamily #2}}
```
修改为
```
\DeclareCaptionLabelFormat{shu}{{\dawu[1.5] #1~\rmfamily #2}}
```

**Comment by cocohao715** [comment]
![image](https://github.com/BlueFisher/shuthesis/assets/32030622/ff1e94a0-d586-4e83-98c7-32290c00332d)
修改完，发现字体大小不一样

**Comment by BlueFisher** [comment]
中文与英文是不同字体，这样排版是正常现象
