### ISSUE TITLE
Caption

### ISSUE THREAD

**Issue by Resurgence3** [BlueFisher/shuthesis#34]
作者您好，我发现文中图片的caption如果太长的话就不会居中了，caption长度如果不超过一行是正常的
![微信图片_20240328230555](https://github.com/BlueFisher/shuthesis/assets/104670664/caf7719f-06fd-436e-8929-f45287332f17)
![微信图片_20240328230602](https://github.com/BlueFisher/shuthesis/assets/104670664/988ac80c-860a-42d7-bf25-c801872a7908)

**Comment by BlueFisher** [comment]
参考 [https://tex.stackexchange.com/questions/95207/how-to-center-a-specific-caption](https://tex.stackexchange.com/questions/95207/how-to-center-a-specific-caption)
