### ISSUE TITLE
sidewaystable排版表格奇偶页不同开合问题

### ISSUE THREAD

**Issue by haikunzhang95** [BlueFisher/shuthesis#35]
sidewaystable排版表格，偶数页是从右往左排列的表格，即右侧开始表头-》表格。奇数页刚好相反。怎么设置这样的表格在任何页面都是统一的从页面右侧到左侧开始排列？
谢谢。

**Comment by BlueFisher** [comment]
可以尝试给宏包rotating增加参数，比如 `\usepackage[figuresleft]{rotating}`

**Comment by haikunzhang95** [comment]
> 可以尝试给宏包rotating增加参数，比如 `\usepackage[figuresleft]{rotating}`

按照您的方法有效，已经解决了，谢谢。
