### ISSUE TITLE
增加参加的科研项目部分

### ISSUE THREAD

**Issue by haikunzhang95** [BlueFisher/shuthesis#36]
除了发表论文和申请专利外，基本上同学们都参与了项目。老师要求参加的项目应单独列出，不应该和“研究成果”放一起，因此如何增加在“publications”后加上单独的一页列出参加的项目？
谢谢！

**Comment by BlueFisher** [comment]
可以看 https://github.com/BlueFisher/shuthesis/commit/8283eadc1b357e6f0bd1e405ea1e556495c36572 这个commit前的记录，以前学校的模板是有projects这一页的，但是现在的模板删除了，所以latex中也删除了

**Comment by haikunzhang95** [comment]
> 可以看 [8283ead](https://github.com/BlueFisher/shuthesis/commit/8283eadc1b357e6f0bd1e405ea1e556495c36572) 这个commit前的记录，以前学校的模板是有projects这一页的，但是现在的模板删除了，所以latex中也删除了

那把“攻读博士学位期间取得的研究成果”改为“攻读博士学位期间取得的研究成果和参加的科研项目”怎么更改呢？
谢谢

**Comment by BlueFisher** [comment]
修改 `shuthesis.cfg` 中的 `\newcommand{\shu@publications@title}{攻读\shu@cdegree 学位期间取得的研究成果}`

**Comment by haikunzhang95** [comment]
> 修改 `shuthesis.cfg` 中的 `\newcommand{\shu@publications@title}{攻读\shu@cdegree 学位期间取得的研究成果}`

谢谢，已经解决。
