### ISSUE TITLE
参考文献作者姓名如何改为全为大写？

### ISSUE THREAD

**Issue by haikunzhang95** [BlueFisher/shuthesis#37]
您好，我的参考文献是用\bibitem插入的，作者是姓首字母大写（例如：Zhang S），学校最新模板是命名都大写（ZHANG S），请问如何更改？
谢谢。

**Comment by BlueFisher** [comment]
参考文献由 https://github.com/zepinglee/gbt7714-bibtex-style 宏包提供，具体参考该项目。推荐使用.bib管理文献

**Comment by cqzw555** [comment]
可以使用biblatex，将原本的natbib注释掉，在导言区加上
```
\usepackage[backend=bibtex, style=gb7714-2015]{biblatex} % biblatex
\ExecuteBibliographyOptions{
	gbpunctin    = false,
	gbfieldtype  = false,
	gbnamefmt=lowercase 
}
```
