### ISSUE TITLE
标题编号更换样式

### ISSUE THREAD

**Issue by XinhuaHe** [BlueFisher/shuthesis#38]
学校模板中标题的编号已经是Times new Roman格式了，该模板中section，subsection中编号及英文如何能改为相应字体，而中文仍保持黑体？

**Comment by BlueFisher** [comment]
latex中目前section的中英文为了统一，都使用的是无衬线字体`\ttfamily`

如果需要将序号变为衬线字体，可在 `shuthesis.cls` 中在 `\ctexset`的`section`设置中增加
```
numberformat=\rmfamily
```
英文字体的话需要手动将 `\section{标题abc标题}` 变为 `\section{标题\textrm{abc}标题}`
