### ISSUE TITLE
引用arxiv文献格式问题

### ISSUE THREAD

**Issue by ohjarwa** [BlueFisher/shuthesis#40]
hi bluefisher
我在引用arxiv文献时碰到如下问题：
e.g.
bibtex如下：
![image](https://github.com/BlueFisher/shuthesis/assets/48442674/feb5262d-a1ee-4193-b8be-cd3d6871900e)
参考文献中显示如下：
![image](https://github.com/BlueFisher/shuthesis/assets/48442674/f161b207-fc3f-4eca-bf5e-fd610206e27a)
预期结果中应出现arxiv的预印号，如下：
![image](https://github.com/BlueFisher/shuthesis/assets/48442674/b570d318-392f-4b88-9d2a-d9f1da997a7c)

请问该如何解决这个问题？

**Comment by BlueFisher** [comment]
journal一般为CoRR，预印号可写在volume中

**Comment by ohjarwa** [comment]
已解决问题，谢谢bluefisher
