### ISSUE TITLE
图片表格标题的字号调整

### ISSUE THREAD

**Issue by XinhuaHe** [BlueFisher/shuthesis#43]
作者您好，想咨询您两个问题：1、Latex上如何输入实心的心形符号  2、图片表格标题的字号想减小一号字体，请问在哪里调节呢？

**Comment by BlueFisher** [comment]
1. 可参考 [https://tex.stackexchange.com/a/9642](https://tex.stackexchange.com/a/9642)
2. 可查找并修改
```
\DeclareCaptionLabelFormat{shu}{{\dawu[1.5]\heiti #1~\rmfamily #2}}
\DeclareCaptionLabelSeparator{shu}{\hspace{1em}}
\DeclareCaptionFont{shu}{\dawu[1.5]}
```

**Comment by XinhuaHe** [comment]
为什么我改了之后，图1.1这几个字体可以调整小 但图1.1后面的具体内容就没变了 还保持dawu的格式 这是怎么回事呢 比如：图1.1 合成示意图   合成示意图几个字就没变化

**Comment by BlueFisher** [comment]
`DeclareCaptionLabelFormat` 改变的是 `图1.1`
`DeclareCaptionFont` 改变的是 `合成示意图`

**Comment by XinhuaHe** [comment]
但是我修改了 请问没有变化是怎么回事呢

**Comment by XinhuaHe** [comment]
难道因为我是中英文双标题吗？

**Comment by BlueFisher** [comment]
改成这样
```
\DeclareCaptionLabelFormat{shu}{{\xiaoliu[1.5]\heiti #1~\rmfamily #2}}
\DeclareCaptionLabelSeparator{shu}{\hspace{1em}}
\DeclareCaptionFont{shu}{\xiaoliu[1.5]}
```
label和caption都会变小
