### ISSUE TITLE
封面部分字体格式有误

### ISSUE THREAD

**Issue by yhmmya** [BlueFisher/shuthesis#49]
将latex clone以后直接编译，封面部分（作者名字、导师名字等）字体是楷体，而标准word模板这里是黑体，这是bug还是哪里需要设置，谢谢

**Comment by BlueFisher** [comment]
为了美观才设置的楷体，不一定一定要与标准word一致，如果你不希望用开题，可以搜素`shuthesis.cls`中的`\makebox[4em][s]{作者} `，将`/kaishu`删除即可

**Comment by yhmmya** [comment]
好的，已解决！感谢，不过有个小建议，因为我，包括我身边同学使用这个latex主要还是用于直接写毕业论文（包括后续查重送盲等），不再使用word。所以在格式这方面还是希望尽量贴合标准毕业论文模板。相信大多数同学会跟我想法一致
