### ISSUE TITLE
关于英文摘要字体

### ISSUE THREAD

**Issue by UAMYEVTHING** [BlueFisher/shuthesis#7]
请问英文摘要ABSTRACT字体如何更改为Time New Roman不加粗呢？

**Comment by BlueFisher** [comment]
https://github.com/BlueFisher/shuthesis/blob/master/shuthesis.cls#L300 改为 `{\textrm{#1}}%`。
但感觉现在的挺好看。

**Comment by UAMYEVTHING** [comment]
是挺好看，可是学校研究生院的模板是Time New Roman呢，所以想改下

**Comment by cocohao715** [comment]
请问，这个怎么改，我直接替换了会报错

**Comment by BlueFisher** [comment]
```
\shu@chapter*{\eabstractname}
```
修改为
```
\shu@chapter*{\textbf{\textrm{\eabstractname}}}
```

**Comment by BlueFisher** [comment]
```
{\bfseries #1}%
```
修改为
```
{\textrm{#1}}%
```

**Comment by cocohao715** [comment]
怎么加粗呢

**Comment by BlueFisher** [comment]
`{\bfseries \textrm{#1}}%`

**Comment by cocohao715** [comment]
大佬，中文摘要怎么加粗

**Comment by cocohao715** [comment]
按大佬的改法，`\shu@chapter*{\cabstractname}`修改成`\shu@chapter*{\bfseries \cabstractname}`

**Comment by BlueFisher** [comment]
中文的加粗其实黑体，没有word中的变粗样式。
不过可以尝试将
```
\shu@chapter*{\cabstractname}
```
修改为
```
\shu@chapter*{\LanTingHei \cabstractname}
```
换一种字体的方式，显得更粗

**Comment by cocohao715** [comment]
大佬 用\LanTingHei会报错，这个怎么解决

**Comment by BlueFisher** [comment]
查看是否使用的是xelatex编译

**Comment by cocohao715** [comment]
已修改，太强了
