### ISSUE TITLE
关于正文行间距

### ISSUE THREAD

**Issue by UAMYEVTHING** [BlueFisher/shuthesis#8]
请问如何调整正文的段落间距和段落中文字的行间距呢？

**Comment by BlueFisher** [comment]
行距：https://github.com/BlueFisher/shuthesis/blob/master/shuthesis.cls#L196 `20bp`为行距

段落间距：添加 `\setlength{\parskip}{10pt}`

**Comment by UAMYEVTHING** [comment]
谢谢，已找到
