### ISSUE TITLE
One more questioin

### ISSUE THREAD

**Issue by UAMYEVTHING** [BlueFisher/shuthesis#9]
请问如何调整 section和subsubsection的自动标题中的数字字体为Time New Roman呢，找了好久找不到。。。

**Comment by BlueFisher** [comment]
建议直接强制指定 `\section{模板说明\textrm{Abc}}`

**Comment by UAMYEVTHING** [comment]
这样的话，应该是更改section的内容的字体了吧，比如正文中有：1.1 模板说明1.1，后面的1.1是可以通过这种方法改动的，前面的1.1是自动生成的，还是原来的默认字体，怎么更改呢

**Comment by UAMYEVTHING** [comment]
已经解决，将section下面定义的format改为normalsize
